# Generated by Django 5.0.6 on 2024-06-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=8, unique=True)),
                ('username', models.CharField(max_length=15)),
                ('firstName', models.CharField(max_length=15)),
                ('lastName', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('dateOfBirth', models.DateField()),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('profilePicture', models.ImageField(upload_to='')),
                ('bio', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=10)),
                ('totalPosts', models.IntegerField()),
            ],
        ),
    ]
